// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_mes.proto

package org.eclipse.orion.server.cf.loggregator;

public final class LoggregatorMessage {
	private LoggregatorMessage() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface MessageOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required bytes message = 1;
		boolean hasMessage();

		com.google.protobuf.ByteString getMessage();

		// required .logmessage.Message.MessageType message_type = 2;
		boolean hasMessageType();

		org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType getMessageType();

		// required sint64 timestamp = 3;
		boolean hasTimestamp();

		long getTimestamp();

		// required string app_id = 4;
		boolean hasAppId();

		String getAppId();

		// optional string source_id = 6;
		boolean hasSourceId();

		String getSourceId();

		// repeated string drain_urls = 7;
		java.util.List<String> getDrainUrlsList();

		int getDrainUrlsCount();

		String getDrainUrls(int index);

		// optional string source_name = 8;
		boolean hasSourceName();

		String getSourceName();
	}

	public static final class Message extends com.google.protobuf.GeneratedMessage implements MessageOrBuilder {
		// Use Message.newBuilder() to construct.
		private Message(Builder builder) {
			super(builder);
		}

		private Message(boolean noInit) {
		}

		private static final Message defaultInstance;

		public static Message getDefaultInstance() {
			return defaultInstance;
		}

		public Message getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.internal_static_logmessage_Message_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.internal_static_logmessage_Message_fieldAccessorTable;
		}

		public enum MessageType implements com.google.protobuf.ProtocolMessageEnum {
			OUT(0, 1), ERR(1, 2), ;

			public static final int OUT_VALUE = 1;
			public static final int ERR_VALUE = 2;

			public final int getNumber() {
				return value;
			}

			public static MessageType valueOf(int value) {
				switch (value) {
					case 1 :
						return OUT;
					case 2 :
						return ERR;
					default :
						return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<MessageType> internalGetValueMap() {
				return internalValueMap;
			}

			private static com.google.protobuf.Internal.EnumLiteMap<MessageType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
				public MessageType findValueByNumber(int number) {
					return MessageType.valueOf(number);
				}
			};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDescriptor().getEnumTypes().get(0);
			}

			private static final MessageType[] VALUES = {OUT, ERR,};

			public static MessageType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private MessageType(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:logmessage.Message.MessageType)
		}

		private int bitField0_;
		// required bytes message = 1;
		public static final int MESSAGE_FIELD_NUMBER = 1;
		private com.google.protobuf.ByteString message_;

		public boolean hasMessage() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public com.google.protobuf.ByteString getMessage() {
			return message_;
		}

		// required .logmessage.Message.MessageType message_type = 2;
		public static final int MESSAGE_TYPE_FIELD_NUMBER = 2;
		private org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType messageType_;

		public boolean hasMessageType() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType getMessageType() {
			return messageType_;
		}

		// required sint64 timestamp = 3;
		public static final int TIMESTAMP_FIELD_NUMBER = 3;
		private long timestamp_;

		public boolean hasTimestamp() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public long getTimestamp() {
			return timestamp_;
		}

		// required string app_id = 4;
		public static final int APP_ID_FIELD_NUMBER = 4;
		private Object appId_;

		public boolean hasAppId() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public String getAppId() {
			Object ref = appId_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					appId_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getAppIdBytes() {
			Object ref = appId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				appId_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string source_id = 6;
		public static final int SOURCE_ID_FIELD_NUMBER = 6;
		private Object sourceId_;

		public boolean hasSourceId() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public String getSourceId() {
			Object ref = sourceId_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					sourceId_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getSourceIdBytes() {
			Object ref = sourceId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				sourceId_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// repeated string drain_urls = 7;
		public static final int DRAIN_URLS_FIELD_NUMBER = 7;
		private com.google.protobuf.LazyStringList drainUrls_;

		public java.util.List<String> getDrainUrlsList() {
			return drainUrls_;
		}

		public int getDrainUrlsCount() {
			return drainUrls_.size();
		}

		public String getDrainUrls(int index) {
			return drainUrls_.get(index);
		}

		// optional string source_name = 8;
		public static final int SOURCE_NAME_FIELD_NUMBER = 8;
		private Object sourceName_;

		public boolean hasSourceName() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}

		public String getSourceName() {
			Object ref = sourceName_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					sourceName_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getSourceNameBytes() {
			Object ref = sourceName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				sourceName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			message_ = com.google.protobuf.ByteString.EMPTY;
			messageType_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType.OUT;
			timestamp_ = 0L;
			appId_ = "";
			sourceId_ = "";
			drainUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
			sourceName_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasMessage()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMessageType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasTimestamp()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasAppId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, message_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeEnum(2, messageType_.getNumber());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeSInt64(3, timestamp_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(4, getAppIdBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(6, getSourceIdBytes());
			}
			for (int i = 0; i < drainUrls_.size(); i++) {
				output.writeBytes(7, drainUrls_.getByteString(i));
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeBytes(8, getSourceNameBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, message_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, messageType_.getNumber());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeSInt64Size(3, timestamp_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(4, getAppIdBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(6, getSourceIdBytes());
			}
			{
				int dataSize = 0;
				for (int i = 0; i < drainUrls_.size(); i++) {
					dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(drainUrls_.getByteString(i));
				}
				size += dataSize;
				size += 1 * getDrainUrlsList().size();
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(8, getSourceNameBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		@java.lang.Override
		protected Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseFrom(java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.MessageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.internal_static_logmessage_Message_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.internal_static_logmessage_Message_fieldAccessorTable;
			}

			// Construct using org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				message_ = com.google.protobuf.ByteString.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000001);
				messageType_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType.OUT;
				bitField0_ = (bitField0_ & ~0x00000002);
				timestamp_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000004);
				appId_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				sourceId_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				drainUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000020);
				sourceName_ = "";
				bitField0_ = (bitField0_ & ~0x00000040);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDescriptor();
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message getDefaultInstanceForType() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDefaultInstance();
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message build() {
				org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message buildParsed() throws com.google.protobuf.InvalidProtocolBufferException {
				org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message buildPartial() {
				org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message result = new org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.message_ = message_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.messageType_ = messageType_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.timestamp_ = timestamp_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.appId_ = appId_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.sourceId_ = sourceId_;
				if (((bitField0_ & 0x00000020) == 0x00000020)) {
					drainUrls_ = new com.google.protobuf.UnmodifiableLazyStringList(drainUrls_);
					bitField0_ = (bitField0_ & ~0x00000020);
				}
				result.drainUrls_ = drainUrls_;
				if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
					to_bitField0_ |= 0x00000020;
				}
				result.sourceName_ = sourceName_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message) {
					return mergeFrom((org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message other) {
				if (other == org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDefaultInstance())
					return this;
				if (other.hasMessage()) {
					setMessage(other.getMessage());
				}
				if (other.hasMessageType()) {
					setMessageType(other.getMessageType());
				}
				if (other.hasTimestamp()) {
					setTimestamp(other.getTimestamp());
				}
				if (other.hasAppId()) {
					setAppId(other.getAppId());
				}
				if (other.hasSourceId()) {
					setSourceId(other.getSourceId());
				}
				if (!other.drainUrls_.isEmpty()) {
					if (drainUrls_.isEmpty()) {
						drainUrls_ = other.drainUrls_;
						bitField0_ = (bitField0_ & ~0x00000020);
					} else {
						ensureDrainUrlsIsMutable();
						drainUrls_.addAll(other.drainUrls_);
					}
					onChanged();
				}
				if (other.hasSourceName()) {
					setSourceName(other.getSourceName());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasMessage()) {

					return false;
				}
				if (!hasMessageType()) {

					return false;
				}
				if (!hasTimestamp()) {

					return false;
				}
				if (!hasAppId()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = 0;
					try {
						tag = input.readTag();
					} catch (Exception e) {
						// do nothing
					}
					switch (tag) {
						case 0 :
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						default : {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								this.setUnknownFields(unknownFields.build());
								onChanged();
								return this;
							}
							break;
						}
						case 10 : {
							bitField0_ |= 0x00000001;
							message_ = input.readBytes();
							break;
						}
						case 16 : {
							int rawValue = input.readEnum();
							org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType value = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType.valueOf(rawValue);
							if (value == null) {
								unknownFields.mergeVarintField(2, rawValue);
							} else {
								bitField0_ |= 0x00000002;
								messageType_ = value;
							}
							break;
						}
						case 24 : {
							bitField0_ |= 0x00000004;
							timestamp_ = input.readSInt64();
							break;
						}
						case 34 : {
							bitField0_ |= 0x00000008;
							appId_ = input.readBytes();
							break;
						}
						case 50 : {
							bitField0_ |= 0x00000010;
							sourceId_ = input.readBytes();
							break;
						}
						case 58 : {
							ensureDrainUrlsIsMutable();
							drainUrls_.add(input.readBytes());
							break;
						}
						case 66 : {
							bitField0_ |= 0x00000040;
							sourceName_ = input.readBytes();
							break;
						}
					}
				}
			}

			private int bitField0_;

			// required bytes message = 1;
			private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;

			public boolean hasMessage() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public com.google.protobuf.ByteString getMessage() {
				return message_;
			}

			public Builder setMessage(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				message_ = value;
				onChanged();
				return this;
			}

			public Builder clearMessage() {
				bitField0_ = (bitField0_ & ~0x00000001);
				message_ = getDefaultInstance().getMessage();
				onChanged();
				return this;
			}

			// required .logmessage.Message.MessageType message_type = 2;
			private org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType messageType_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType.OUT;

			public boolean hasMessageType() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType getMessageType() {
				return messageType_;
			}

			public Builder setMessageType(org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				messageType_ = value;
				onChanged();
				return this;
			}

			public Builder clearMessageType() {
				bitField0_ = (bitField0_ & ~0x00000002);
				messageType_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.MessageType.OUT;
				onChanged();
				return this;
			}

			// required sint64 timestamp = 3;
			private long timestamp_;

			public boolean hasTimestamp() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public long getTimestamp() {
				return timestamp_;
			}

			public Builder setTimestamp(long value) {
				bitField0_ |= 0x00000004;
				timestamp_ = value;
				onChanged();
				return this;
			}

			public Builder clearTimestamp() {
				bitField0_ = (bitField0_ & ~0x00000004);
				timestamp_ = 0L;
				onChanged();
				return this;
			}

			// required string app_id = 4;
			private Object appId_ = "";

			public boolean hasAppId() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public String getAppId() {
				Object ref = appId_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					appId_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setAppId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				appId_ = value;
				onChanged();
				return this;
			}

			public Builder clearAppId() {
				bitField0_ = (bitField0_ & ~0x00000008);
				appId_ = getDefaultInstance().getAppId();
				onChanged();
				return this;
			}

			void setAppId(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000008;
				appId_ = value;
				onChanged();
			}

			// optional string source_id = 6;
			private Object sourceId_ = "";

			public boolean hasSourceId() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public String getSourceId() {
				Object ref = sourceId_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					sourceId_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setSourceId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				sourceId_ = value;
				onChanged();
				return this;
			}

			public Builder clearSourceId() {
				bitField0_ = (bitField0_ & ~0x00000010);
				sourceId_ = getDefaultInstance().getSourceId();
				onChanged();
				return this;
			}

			void setSourceId(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000010;
				sourceId_ = value;
				onChanged();
			}

			// repeated string drain_urls = 7;
			private com.google.protobuf.LazyStringList drainUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;

			private void ensureDrainUrlsIsMutable() {
				if (!((bitField0_ & 0x00000020) == 0x00000020)) {
					drainUrls_ = new com.google.protobuf.LazyStringArrayList(drainUrls_);
					bitField0_ |= 0x00000020;
				}
			}

			public java.util.List<String> getDrainUrlsList() {
				return java.util.Collections.unmodifiableList(drainUrls_);
			}

			public int getDrainUrlsCount() {
				return drainUrls_.size();
			}

			public String getDrainUrls(int index) {
				return drainUrls_.get(index);
			}

			public Builder setDrainUrls(int index, String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureDrainUrlsIsMutable();
				drainUrls_.set(index, value);
				onChanged();
				return this;
			}

			public Builder addDrainUrls(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureDrainUrlsIsMutable();
				drainUrls_.add(value);
				onChanged();
				return this;
			}

			public Builder addAllDrainUrls(java.lang.Iterable<String> values) {
				ensureDrainUrlsIsMutable();
				super.addAll(values, drainUrls_);
				onChanged();
				return this;
			}

			public Builder clearDrainUrls() {
				drainUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000020);
				onChanged();
				return this;
			}

			void addDrainUrls(com.google.protobuf.ByteString value) {
				ensureDrainUrlsIsMutable();
				drainUrls_.add(value);
				onChanged();
			}

			// optional string source_name = 8;
			private Object sourceName_ = "";

			public boolean hasSourceName() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}

			public String getSourceName() {
				Object ref = sourceName_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					sourceName_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setSourceName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000040;
				sourceName_ = value;
				onChanged();
				return this;
			}

			public Builder clearSourceName() {
				bitField0_ = (bitField0_ & ~0x00000040);
				sourceName_ = getDefaultInstance().getSourceName();
				onChanged();
				return this;
			}

			void setSourceName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000040;
				sourceName_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:logmessage.Message)
		}

		static {
			defaultInstance = new Message(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:logmessage.Message)
	}

	public interface EnvelopeOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required string routing_key = 1;
		boolean hasRoutingKey();

		String getRoutingKey();

		// required bytes signature = 2;
		boolean hasSignature();

		com.google.protobuf.ByteString getSignature();

		// required .logmessage.Message log_message = 3;
		boolean hasLogMessage();

		org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message getLogMessage();

		org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.MessageOrBuilder getLogMessageOrBuilder();
	}

	public static final class Envelope extends com.google.protobuf.GeneratedMessage implements EnvelopeOrBuilder {
		// Use Envelope.newBuilder() to construct.
		private Envelope(Builder builder) {
			super(builder);
		}

		private Envelope(boolean noInit) {
		}

		private static final Envelope defaultInstance;

		public static Envelope getDefaultInstance() {
			return defaultInstance;
		}

		public Envelope getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.internal_static_logmessage_Envelope_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.internal_static_logmessage_Envelope_fieldAccessorTable;
		}

		private int bitField0_;
		// required string routing_key = 1;
		public static final int ROUTING_KEY_FIELD_NUMBER = 1;
		private Object routingKey_;

		public boolean hasRoutingKey() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public String getRoutingKey() {
			Object ref = routingKey_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					routingKey_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getRoutingKeyBytes() {
			Object ref = routingKey_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				routingKey_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required bytes signature = 2;
		public static final int SIGNATURE_FIELD_NUMBER = 2;
		private com.google.protobuf.ByteString signature_;

		public boolean hasSignature() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public com.google.protobuf.ByteString getSignature() {
			return signature_;
		}

		// required .logmessage.Message log_message = 3;
		public static final int LOG_MESSAGE_FIELD_NUMBER = 3;
		private org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message logMessage_;

		public boolean hasLogMessage() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message getLogMessage() {
			return logMessage_;
		}

		public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.MessageOrBuilder getLogMessageOrBuilder() {
			return logMessage_;
		}

		private void initFields() {
			routingKey_ = "";
			signature_ = com.google.protobuf.ByteString.EMPTY;
			logMessage_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDefaultInstance();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasRoutingKey()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasSignature()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasLogMessage()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!getLogMessage().isInitialized()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getRoutingKeyBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, signature_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeMessage(3, logMessage_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getRoutingKeyBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, signature_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, logMessage_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		@java.lang.Override
		protected Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseFrom(java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.EnvelopeOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.internal_static_logmessage_Envelope_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.internal_static_logmessage_Envelope_fieldAccessorTable;
			}

			// Construct using org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getLogMessageFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				routingKey_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				signature_ = com.google.protobuf.ByteString.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000002);
				if (logMessageBuilder_ == null) {
					logMessage_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDefaultInstance();
				} else {
					logMessageBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope.getDescriptor();
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope getDefaultInstanceForType() {
				return org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope.getDefaultInstance();
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope build() {
				org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope buildParsed() throws com.google.protobuf.InvalidProtocolBufferException {
				org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope buildPartial() {
				org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope result = new org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.routingKey_ = routingKey_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.signature_ = signature_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				if (logMessageBuilder_ == null) {
					result.logMessage_ = logMessage_;
				} else {
					result.logMessage_ = logMessageBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope) {
					return mergeFrom((org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope other) {
				if (other == org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope.getDefaultInstance())
					return this;
				if (other.hasRoutingKey()) {
					setRoutingKey(other.getRoutingKey());
				}
				if (other.hasSignature()) {
					setSignature(other.getSignature());
				}
				if (other.hasLogMessage()) {
					mergeLogMessage(other.getLogMessage());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasRoutingKey()) {

					return false;
				}
				if (!hasSignature()) {

					return false;
				}
				if (!hasLogMessage()) {

					return false;
				}
				if (!getLogMessage().isInitialized()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
						case 0 :
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						default : {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								this.setUnknownFields(unknownFields.build());
								onChanged();
								return this;
							}
							break;
						}
						case 10 : {
							bitField0_ |= 0x00000001;
							routingKey_ = input.readBytes();
							break;
						}
						case 18 : {
							bitField0_ |= 0x00000002;
							signature_ = input.readBytes();
							break;
						}
						case 26 : {
							org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.Builder subBuilder = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.newBuilder();
							if (hasLogMessage()) {
								subBuilder.mergeFrom(getLogMessage());
							}
							input.readMessage(subBuilder, extensionRegistry);
							setLogMessage(subBuilder.buildPartial());
							break;
						}
					}
				}
			}

			private int bitField0_;

			// required string routing_key = 1;
			private Object routingKey_ = "";

			public boolean hasRoutingKey() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public String getRoutingKey() {
				Object ref = routingKey_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					routingKey_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setRoutingKey(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				routingKey_ = value;
				onChanged();
				return this;
			}

			public Builder clearRoutingKey() {
				bitField0_ = (bitField0_ & ~0x00000001);
				routingKey_ = getDefaultInstance().getRoutingKey();
				onChanged();
				return this;
			}

			void setRoutingKey(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				routingKey_ = value;
				onChanged();
			}

			// required bytes signature = 2;
			private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;

			public boolean hasSignature() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public com.google.protobuf.ByteString getSignature() {
				return signature_;
			}

			public Builder setSignature(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				signature_ = value;
				onChanged();
				return this;
			}

			public Builder clearSignature() {
				bitField0_ = (bitField0_ & ~0x00000002);
				signature_ = getDefaultInstance().getSignature();
				onChanged();
				return this;
			}

			// required .logmessage.Message log_message = 3;
			private org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message logMessage_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.Builder, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.MessageOrBuilder> logMessageBuilder_;

			public boolean hasLogMessage() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message getLogMessage() {
				if (logMessageBuilder_ == null) {
					return logMessage_;
				} else {
					return logMessageBuilder_.getMessage();
				}
			}

			public Builder setLogMessage(org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message value) {
				if (logMessageBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					logMessage_ = value;
					onChanged();
				} else {
					logMessageBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			public Builder setLogMessage(org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.Builder builderForValue) {
				if (logMessageBuilder_ == null) {
					logMessage_ = builderForValue.build();
					onChanged();
				} else {
					logMessageBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			public Builder mergeLogMessage(org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message value) {
				if (logMessageBuilder_ == null) {
					if (((bitField0_ & 0x00000004) == 0x00000004) && logMessage_ != org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDefaultInstance()) {
						logMessage_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.newBuilder(logMessage_).mergeFrom(value).buildPartial();
					} else {
						logMessage_ = value;
					}
					onChanged();
				} else {
					logMessageBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			public Builder clearLogMessage() {
				if (logMessageBuilder_ == null) {
					logMessage_ = org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.getDefaultInstance();
					onChanged();
				} else {
					logMessageBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.Builder getLogMessageBuilder() {
				bitField0_ |= 0x00000004;
				onChanged();
				return getLogMessageFieldBuilder().getBuilder();
			}

			public org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.MessageOrBuilder getLogMessageOrBuilder() {
				if (logMessageBuilder_ != null) {
					return logMessageBuilder_.getMessageOrBuilder();
				} else {
					return logMessage_;
				}
			}

			private com.google.protobuf.SingleFieldBuilder<org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.Builder, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.MessageOrBuilder> getLogMessageFieldBuilder() {
				if (logMessageBuilder_ == null) {
					logMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.Builder, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.MessageOrBuilder>(logMessage_, getParentForChildren(), isClean());
					logMessage_ = null;
				}
				return logMessageBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:logmessage.Envelope)
		}

		static {
			defaultInstance = new Envelope(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:logmessage.Envelope)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_logmessage_Message_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_logmessage_Message_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_logmessage_Envelope_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_logmessage_Envelope_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {"\n\rlog_mes.proto\022\nlogmessage\"\321\001\n\007Message\022" + "\017\n\007message\030\001 \002(\014\0225\n\014message_type\030\002 \002(\0162\037" + ".logmessage.Message.MessageType\022\021\n\ttimes" + "tamp\030\003 \002(\022\022\016\n\006app_id\030\004 \002(\t\022\021\n\tsource_id\030" + "\006 \001(\t\022\022\n\ndrain_urls\030\007 \003(\t\022\023\n\013source_name" + "\030\010 \001(\t\"\037\n\013MessageType\022\007\n\003OUT\020\001\022\007\n\003ERR\020\002\"" + "\\\n\010Envelope\022\023\n\013routing_key\030\001 \002(\t\022\021\n\tsign" + "ature\030\002 \002(\014\022(\n\013log_message\030\003 \002(\0132\023.logme" + "ssage.MessageB=\n\'org.eclipse.orion.serve" + "r.cf.loggregatorB\022LoggregatorMessage"};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_logmessage_Message_descriptor = getDescriptor().getMessageTypes().get(0);
				internal_static_logmessage_Message_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_logmessage_Message_descriptor, new java.lang.String[] {"Message", "MessageType", "Timestamp", "AppId", "SourceId", "DrainUrls", "SourceName",}, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.class, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Message.Builder.class);
				internal_static_logmessage_Envelope_descriptor = getDescriptor().getMessageTypes().get(1);
				internal_static_logmessage_Envelope_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_logmessage_Envelope_descriptor, new java.lang.String[] {"RoutingKey", "Signature", "LogMessage",}, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope.class, org.eclipse.orion.server.cf.loggregator.LoggregatorMessage.Envelope.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
